### ISSUE TITLE
大佬，我目前发现一个问题

### ISSUE THREAD

**Issue by Shura23** [hululu1068/AdGuard-Rule#14]
我使用你的代码，在mylist中放行一些网站，但是生成的adgh,txt中依旧存在禁止mylist中网站的一些规则，我原本是想假如mylist中有一条规则@@||A.com，用来放行A.com，然后我收集的过滤器中有||A.com，然后生成的规则文件，就把||A.com去除，可是你的代码并没有这个功能，我想问一下你能更新修改一下代码吗？

**Comment by YishaBei** [comment]
可以嘗試叠加 `$important`，使其優先級最高以達到你的需求。以下是示例: 
```example
@@||example.com^$important
```
參考鏈: https://adguard.com/kb/general/ad-filtering/create-own-filters/#important-modifier

至於版本更新的話，別抱有太大希望，核心執行程式仍然停留在[第一次commit](https://github.com/hululu1068/AdGuard-Rule/tree/main/src/main/java/org/fordes/adg/rule)，何況簡中注釋一堆，owner大概率是放棄這個項目了，**<ins>可以說是發佈以來從來沒有更新過</ins>**，你如果有能力的話可以嘗試自己去修改，主項目更新的話概率很渺茫。

**Comment by xiulou23** [comment]
> 可以嘗試叠加 `$important`，使其優先級最高以達到你的需求。以下是示例:
> 
> ```
> @@||example.com^$important
> ```
> 
> 參考鏈: https://adguard.com/kb/general/ad-filtering/create-own-filters/#important-modifier
> 
> 至於版本更新的話，別抱有太大希望，核心執行程式仍然停留在[第一次commit](https://github.com/hululu1068/AdGuard-Rule/tree/main/src/main/java/org/fordes/adg/rule)，何況簡中注釋一堆，owner大概率是放棄這個項目了，**可以說是發佈以來從來沒有更新過**，你如果有能力的話可以嘗試自己去修改，主項目更新的話概率很渺茫。

其实我是有加important的，但是没有起到作用
