### ISSUE TITLE
一些錯誤攔截

### ISSUE THREAD

**Issue by Vulcankta** [hululu1068/AdGuard-Rule#3]
1.www.bilibili.com這個域名下 存在錯誤攔截,具體表現是推薦視頻不顯示圖片,以及評論區不顯示.如下圖:
![image](https://github.com/hululu1068/AdGuard-Rule/assets/61764871/9a7ef8e2-4558-43d8-bda2-9e5d0a214da0)
![image](https://github.com/hululu1068/AdGuard-Rule/assets/61764871/4a7957a8-140b-4de6-a8ad-5f4d6c1a849f)

我不知道該如何添加規則避免這種情況,我暫時只能用如下規則禁用對www.bilibili.com的封鎖:
@@||www.bilibili.com^$important,document

2.andriod上wechat中的餓了麽小程序無法正常加載,我嘗試加入了以下規則之後可以正常加載了:
@@||119.29.29.29^$important
@@||mmstat.com^$important
@@||ele.me^$important

**Comment by hululu1068** [comment]
Add these to mylist.
