### ISSUE TITLE
感谢大佬开源，我克隆了您的代码，修改了自己的专属规则，保留引用

### ISSUE THREAD

**Issue by guandasheng** [hululu1068/AdGuard-Rule#6]
https://github.com/guandasheng/best-adrules

best-adrules欢迎星标

**Comment by xiulou23** [comment]
> https://github.com/guandasheng/best-adrules
> 
> best-adrules欢迎星标

这个开发者的代码是不是就是用来去重过滤规则的？去重效果怎么样
